export const DefinedCommands = Object.freeze({
    ADD_DOWNLOAD: "add_download",
    SHOW_ALERT: "show_alert",
    SHOW_LOG: "show_log",
    CHECK_SELECTED_TEXT_FOR_LINKS: "check_selected_text_for_links",
    TEST_NATIVE_MESSAGING: "test_native_messaging",
    TEST_HTTP_PORT: "test_http_port",
    IS_APP_REACHABLE: "is_app_reachable",
    GET_HEADERS: "get_headers",
    SET_HOLDING_KEY: "set_holding_key",
    GET_PLATFORM: "get_platform",
    DOWNLOADABLE_MEDIA_DETECTED: "downloadable_media_detected",
    GET_BROWSER_POLICY_STATUS_V2: "get_browser_policy_status_v2",
    UPDATE_BROWSER_POLICY_V2: "update_browser_policy_v2",
    RECONCILE_BROWSER_PERMISSIONS_V2: "reconcile_browser_permissions_v2",
    SET_TAB_CAPTURE_BYPASS_V2: "set_tab_capture_bypass_v2",
    RECAPTURE_BROWSER_DOWNLOAD_V2: "recapture_browser_download_v2",
    SUBMIT_STAGED_BROWSER_BATCH_V2: "submit_staged_browser_batch_v2",
    CANCEL_STAGED_BROWSER_BATCH_V2: "cancel_staged_browser_batch_v2",
    GET_INTEGRATION_DIAGNOSTICS_V2: "get_integration_diagnostics_v2",
    GET_SAFE_DIAGNOSTICS_V2: "get_safe_diagnostics_v2",
    CLEAR_SAFE_DIAGNOSTICS_V2: "clear_safe_diagnostics_v2",
})
